blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.post_list, name='post_list'),
    path('<int:id>', views.post_detail , name='post_detail'),
    path('tags=<slug:tag>', views.post_by_tag , name='post_by_tag'),
    path('category=<slug:category>', views.post_by_category , name='post_by_category'),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path('meals/', include('meals.urls', namespace='meals')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about-us/',include('aboutus.urls', namespace='aboutus')),
    path('reserve_table/', include('reservation.urls', namespace='reservation')),
    path ('', include('home.urls', namespace='home')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Resturant AdminPanel"
admin.site.site_title = "Resturent App Admin"
admin.site.site_index_title = "Welcome to Resturant Admin Panel"

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    auther = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='blog/', blank=True, null=True)
    category = models.ForeignKey(
        'Category', null=True, on_delete=models.SET_NULL)
    tags = TaggableManager(blank=True)


    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'

    def __str__(self):
        return self.title


class Category(models.Model):
    category_name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def __str__(self):
        return str(self.content)

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content'
        ]

blog/views.py
from django.shortcuts import render
from .models import Post, Category, Comment
from taggit.models import Tag
from .forms import CommentForm
from django.core.paginator import Paginator
from django.db.models import Q
# Create your views here.


def post_list(request):
    post_list = Post.objects.all()

    # search
    search_query = request.GET.get('q')
    if search_query:
        post_list = post_list.filter(
            Q(title__icontains = search_query) |
            Q(content__icontains = search_query) |
            Q(tags__name__icontains = search_query)
        ).distinct()




    paginator = Paginator(post_list, 5) # Show no. of contacts per page.

    page = request.GET.get('page')
    post_list = paginator.get_page(page)

    context = {
        'post_list': post_list,
    }
    return render(request, 'Post/post_list.html', context)


def post_detail(request, id):
    post_detail = Post.objects.get(id=id)
    categories = Category.objects.all()
    all_tags = Tag.objects.all()
    comments = Comment.objects.filter(post=post_detail)
    comment_form = CommentForm()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post_detail
            new_comment.save()
    else:
        comment_form = CommentForm()

    context = {
        'post_detail': post_detail,
        'categories': categories,
        'all_tags': all_tags,
        'comments': comments,
        'comment_form': comment_form,

    }

    return render(request, 'Post/post_detail.html', context)


def post_by_tag(request, tag):
    post_by_tag = Post.objects.filter(tags__name__in=[tag])
    context = {
        'post_list': post_by_tag,
    }
    return render(request, 'Post/post_list.html', context)


def post_by_category(request, category):
    post_by_category = Post.objects.filter(category__category_name=category)
    context = {
        'post_list': post_by_category,
    }
    return render(request, 'Post/post_list.html', context)

blog/templates/Post/post_detail.html
{% extends 'base.html' %} 
{% load static%} 
{% load bootstrap4 %}
{% block body%}
<div class="main-wrap">
    <div class="cover_1 cover_sm">
        <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});"
            data-stellar-background-ratio="0.5">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-7 text-center" data-aos="fade-up">
                        <h2 class="heading mb-4">{{post_detail}}</h2>

                        <div class="post-info">
                            <div class="date-info">{{post_detail.created}}</div>
                            <div class="category-info"><span class="seperator">|</span>In <a href="#"
                                    data-title="View all posts in Lifestyle"
                                    title="View all posts in Lifestyle">{{post_detail.category}}</a></div>
                            <div class="author-info"><span class="seperator">|</span>By <a
                                    href="#">{{post_detail.auther}}</a></div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- .cover_1 -->

    <div class="section">
        <div class="container">

            <div class="row">

                <div class="col-md-8">
                    <p> {{post_detail.content}} </p>

                    <div class="tag-widget post-tag-container mb-5 mt-5">

                        <div class="tagcloud">
                            {% for tag in post_detail.tags.all %}
                            <a href="{% url 'blog:post_by_tag' tag %}" class="tag-cloud-link">{{tag.name}}</a>
                            {% endfor %}
                        </div>

                    </div>


                    <div class="pt-5 mt-5">
                        <h3 class="mb-5">Comments</h3>
                        <ul class="comment-list">
                            {% for comment in comments %}
                            <li class="comment">
                                <div class="vcard bio">
                                    <img src="img/person_1.jpg" alt="Image placeholder">
                                </div>
                                <div class="comment-body">
                                    <h3>{{comment.user}}</h3>
                                    <div class="meta">{{comment.created}}</div>
                                    <p>{{comment.content}}</p>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>



                        <!-- END comment-list -->

                        <div class="comment-form-wrap pt-5">
                            <h3 class="mb-5">Leave a comment</h3>
                            <form method="POST" class="p-5 bg-light">
                                    {% csrf_token %}
                                    {% bootstrap_form comment_form %}
                                    {% buttons %}
                                        <button type="submit" class="btn btn-primary">Leave a Comment</button>
                                    {% endbuttons %}
 
                            </form>
                        </div>
                    </div>

                </div>
                <!-- .col-md-8 -->
                <div class="col-md-4 sidebar">
                    <div class="sidebar-box">
                        <form action="{% url 'blog:post_list'%}" method="GET" class="search-form">
                            <div class="form-group">
                                <span class="icon fa fa-search"></span>
                                <input type="text" class="form-control" name = 'q' value = "{{request.GET.q}}" placeholder="Type a keyword and hit enter">
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-box">
                        <div class="categories">
                            <h3>Categories</h3>
                            {% for category in categories %}
                            <li><a href="{% url 'blog:post_by_category' category %}">{{category}} </a></li>

                            {% endfor %}
                        </div>
                    </div>

                    <div class="sidebar-box">
                        <h3>Tag Cloud</h3>
                        <div class="tagcloud">
                            {% for tag in all_tags %}
                            <a href="{% url 'blog:post_by_tag' tag %}" class="tag-cloud-link">{{tag}}</a> {% endfor %}
                        </div>
                    </div>


                </div>

            </div>


        </div>
    </div>
    <!-- .section -->



</div>
<!-- .main-wrap -->

{% endblock body %}

blog/templates/Post/post_list.html
{% extends 'base.html'%} {% load static %} {% block body%}

<div class="main-wrap">
    <div class="cover_1 cover_sm">
        <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-7" data-aos="fade-up">
                        <h2 class="heading">Blog Grid</h2>
                        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo saepe dolorum dolorem, iste officia voluptates! Sint repudiandae, soluta voluptatem delectus iure, eaque, harum expedita, nisi aliquam magni odio perferendis ipsum!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- .cover_1 -->

    <div class="section">
        <div class="container">

            <div class="row mb-5">
                {% for post in post_list%}
                <div class="col-md-4">
                    <div class="media d-block media-bg-white mb-5" data-aos="fade-up" data-aos-delay="400">
                        <figure>
                            <a href="{% url 'blog:post_detail' post.id %}"><img src="{{post.image.url}}" alt="Image placeholder" class="img-fluid"></a>
                        </figure>
                        <div class="media-body">
                            <h3><a href="{% url 'blog:post_detail' post.id %}">{{post}}</a></h3>
                            <p class="post-meta"><span><span class="fa fa-calendar"></span> {{post.created}}</span>
                            </p>
                            <p class="mb-4">{{post.content|truncatewords:10}}</p>
                            <p><a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                        </div>
                    </div>
                    <!-- .media -->
                </div>
                {% endfor %}

            </div>

            <div class="row">
                {% if post_list.has_other_pages %}
                <div class="col-md-12">
                    <ul class="pagination custom-pagination">
                        {% if post_list.has_previous %}
                        <li class="page-item prev"><a class="page-link" href="?page={{post_list.previous_page_number}}"><i class="fa fa-angle-left"></i></a>
                        </li>
                        {% else %}
                        <li class="disabled"></li>
                        {% endif %} {% for pages in post_list.paginator.page_range %} {% if post_list.number == pages %}
                        <li class="page-item active"><a class="page-linkx" href="#">{{pages}}</a></li>
                        {% else %}
                        <li class="page-item active"><a class="page-linkx" href="?page={{pages}}">{{pages}}</a></li>
                        {% endif%} {% endfor%} {% if post_list.has_next %}
                        <li class=" page-item next "><a class=" page-link " href="?page={{post_list.next_page_number}}"><i class=" fa fa-angle-right "></i></a></li>
                        {% else %}
                        <li class="disabled"></li>
                        {% endif %}
                    </ul>


                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- .section -->



</div>
<!-- .main-wrap -->
{% endblock %}